theme: jekyll-theme-minimal
title: dr-juetz's homepage
description: Bookmark this to keep an eye on my project updates!

def fibonacci(n)
  return n if ( 0..1 ).include? n
  (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls
end